#!/bin/sh
#SBATCH -p gpu
#SBATCH --gres=gpu:pascal:2
#SBATCH --mem=160gb
#SBATCH --time=48:00:00
#SBATCH -o /home/mbiriuk/X-VLM/logs/train-abo-small.out

echo 'Working with ABO!'

echo 'Start training!'
python3 run.py --task "itr_abo" --dist "gpu1" --output_dir "output/itr_abo_small" --checkpoint "/ivi/ilps/personal/mbiriuk/repro/X-VLM/4m_base_model_state_step_199999.th"
echo 'Done with training!'

echo 'End of script!'